### PR TITLE
Custom sphinx conf

### PR DESCRIPTION
**Pull request by thewind1984**
To be able to customize conf files it would be nice to have the possibility to set conf file throught ARGs

### CODE REVIEW

**Review by macbre — APPROVED** [review]
Thanks!

**Comment by macbre** [comment]
Hi, @thewind1984. I'm wondering what's the difference between the ability to provide path to sphinx config via a build arg vs being able to just mount your own config file as a volume to the fixed place (`/opt/sphinx/conf/sphinx.conf` in case of an image in this repository)?

**Comment by thewind1984** [comment]
> Hi, @thewind1984. I'm wondering what's the difference between the ability to provide path to sphinx config via a build arg vs being able to just mount your own config file as a volume to the fixed place (`/opt/sphinx/conf/sphinx.conf` in case of an image in this repository)?

Hi, @macbre , thank you for your question and sorry for late reply.
With this fix I just want to be able to provide some different configs for Sphinx (for indexer / searchd) within single Docker container.
Of course, one of them will be default config, but it's better to be able to name it with not default `sphinx.conf` name...

**Comment by macbre** [comment]
Thanks, @thewind1984

**Pull request merged**
